### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by crow131** [mathifonseca/grails-browser-detection#7]
Hi, Is it possible to nest these?

EG:
< browser:isNotWindowsMobile>
        < browser:isMsie versionLower="9">
        ...
        </ browser:isMsie>
</ browser:isNotWindowsMobile>

**Comment by mathifonseca** [comment]
Yes, it should be possible to nest the tags. Have you tried it?

**Comment by crow131** [comment]
I have been using the above in prod since December, I am covering my bases.
I added a check for Safari and re-ordered the lines with choice tag and it starting spewing an error message every second in qa.

Turning off the grails.plugin.springsecurity.debug.useFilter kills the error message but defeats the purpose of testing :)

Sample:
        ```
at grails.plugin.springsecurity.web.filter.DebugFilter.log(DebugFilter.java:145)
        at grails.plugin.springsecurity.web.filter.DebugFilter$1.getSession(DebugFilter.java:89)
        at org.geeks.browserdetection.UserAgentIdentService.getUserAgent(UserAgentIdentService.groovy:57)
        at org.geeks.browserdetection.UserAgentIdentService.isWindowsMobile(UserAgentIdentService.groovy:226)
        at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)
        at org.geeks.browserdetection.BrowserTagLib$_closure15_closure57.doCall(BrowserTagLib.groovy:88)
        at org.geeks.browserdetection.BrowserTagLib.handle(BrowserTagLib.groovy:233)
        at org.geeks.browserdetection.BrowserTagLib$_closure15.doCall(BrowserTagLib.groovy:88)
```

**Comment by mathifonseca** [comment]
Hi @crow131, sorry for the extremely long delay. Are you still having this problem? Have you tried version 2.8.1?
